### SENSORS ###

# SABnzbd #
- platform: sabnzbd
  host: 10.0.1.13
  api_key: !secret sabnzbd_api
  monitored_variables:
    - 'current_status'
    - 'speed'
    - 'queue_size'
    - 'queue_remaining'
    - 'disk_size'
    - 'disk_free'

## Yahoo Weather ##

- platform: yweather
  monitored_conditions:
    - weather
    - weather_current
    - temp_min
    - temp_max
    - temperature
